site_name: containerlab
nav:
  - Home: index.md
  - Installation: install.md
  - Quick start: quickstart.md
  - User manual:
      - Topology definition: manual/topo-def-file.md
      - Nodes: manual/nodes.md
      - Kinds:
          - About: manual/kinds/kinds.md
          - srl - Nokia SR Linux: manual/kinds/srl.md
          - crpd - Juniper cRPD: manual/kinds/crpd.md
          - ceos - Arista cEOS: manual/kinds/ceos.md
          - cvx - Cumulus VX: manual/kinds/cvx.md
          - sonic-vs - SONiC: manual/kinds/sonic-vs.md
          - vr-sros - Nokia SR OS: manual/kinds/vr-sros.md
          - vr-vmx - Juniper vMX: manual/kinds/vr-vmx.md
          - vr-vqfx - Juniper vQFX: manual/kinds/vr-vqfx.md
          - vr-xrv9k - Cisco XRv9k: manual/kinds/vr-xrv9k.md
          - vr-xrv - Cisco XRv: manual/kinds/vr-xrv.md
          - vr-csr - Cisco CSR1000v: manual/kinds/vr-csr.md
          - vr-n9kv - Cisco Nexus 9000v: manual/kinds/vr-n9kv.md
          - vr-ftosv - Dell FTOS10v: manual/kinds/vr-ftosv.md
          - vr-veos - Arista vEOS: manual/kinds/vr-veos.md
          - vr-ros - MikroTik RouterOS: manual/kinds/vr-ros.md
          - vr-pan - Palo Alto PAN: manual/kinds/vr-pan.md
          - linux - Linux container: manual/kinds/linux.md
          - bridge - Linux bridge: manual/kinds/bridge.md
          - ovs-bridge - Openvswitch bridge: manual/kinds/ovs-bridge.md
      - Configuration artifacts: manual/conf-artifacts.md
      - Network wiring concepts: manual/network.md
      - Packet capture & Wireshark: manual/wireshark.md
      - VM based routers integration: manual/vrnetlab.md
      - Publish ports: manual/published-ports.md
      - Multi-node labs: manual/multi-node.md
      - Certificate management: manual/cert.md
      - Inventory: manual/inventory.md
      - Image management: manual/images.md
  - Command reference:
      - deploy: cmd/deploy.md
      - destroy: cmd/destroy.md
      - inspect: cmd/inspect.md
      - save: cmd/save.md
      - exec: cmd/exec.md
      - generate: cmd/generate.md
      - graph: cmd/graph.md
      - tools:
          - disable-tx-offload: cmd/tools/disable-tx-offload.md
          - veth:
              - create: cmd/tools/veth/create.md
          - vxlan:
              - create: cmd/tools/vxlan/create.md
              - delete: cmd/tools/vxlan/delete.md
          - cert:
              - ca:
                  - create: cmd/tools/cert/ca/create.md
              - sign: cmd/tools/cert/sign.md
          - mysocketio:
              - login: cmd/tools/mysocketio/login.md
      - completions: cmd/completion.md
  - Lab examples:
      - About: lab-examples/lab-examples.md
      - Single SR Linux node: lab-examples/single-srl.md
      - Two SR Linux nodes: lab-examples/two-srls.md
      - 3-nodes Clos fabric: lab-examples/min-clos.md
      - 5-stage Clos fabric: lab-examples/min-5clos.md
      - 5-stage SR Linux based Clos fabric with config engine: lab-examples/cfg-clos.md
      - Nokia SR Linux and Arista cEOS: lab-examples/srl-ceos.md
      - Nokia SR Linux and Juniper cRPD: lab-examples/srl-crpd.md
      - Nokia SR Linux and SONiC: lab-examples/srl-sonic.md
      - External bridge capability: lab-examples/ext-bridge.md
      - WAN topology: lab-examples/wan.md
      - Nokia SR Linux and Nokia SR OS: lab-examples/vr-sros.md
      - Nokia SR Linux and Juniper vMX: lab-examples/vr-vmx.md
      - Nokia SR Linux and Cisco XRv9k: lab-examples/vr-xrv9k.md
      - Nokia SR Linux and Cisco XRv: lab-examples/vr-xrv.md
      - Nokia SR Linux and FRR: lab-examples/srl-frr.md
      - FRR: lab-examples/frr01.md
      - Cumulus Linux and FRR: lab-examples/cvx01.md
      - Cumulus Linux (docker runtime) and Host: lab-examples/cvx02.md
      - BGP VPLS between Nokia and Juniper: lab-examples/bgp-vpls-nok-jun.md
      - Multi-node labs: lab-examples/multinode.md
      - Templated labs:
          - Leaf-spine topology: lab-examples/templated01.md
          - 5-stage Clos topology: lab-examples/templated02.md
  - Release notes:
      - "0.21": rn/0.21.md
      - "0.20": rn/0.20.md
      - 0.19: rn/0.19.md
      - 0.18: rn/0.18.md
      - 0.17: rn/0.17.md
      - 0.16: rn/0.16.md
      - 0.15: rn/0.15.md
      - 0.14.4: rn/0.14.4.md
      - 0.14.3: rn/0.14.3.md
      - 0.14.2: rn/0.14.2.md
      - 0.14.1: rn/0.14.1.md
      - 0.14.0: rn/0.14.0.md
      - 0.13.0: rn/0.13.0.md
      - 0.12.0: rn/0.12.0.md
      - 0.11.0: rn/0.11.0.md
  - Community: community.md

site_author: Roman Dodin
site_description: >-
  Containerlab deploys docker based meshed lab topologies
# Repository
repo_name: srl-labs/containerlab
repo_url: https://github.com/srl-labs/containerlab
site_url: "https://containerlab.srlinux.dev/"
edit_uri: ""
theme:
  name: material
  custom_dir: docs/overrides

  # 404 page
  static_templates:
    - 404.html

  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true

  features:
    - navigation.top
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - search.suggest

  language: en
  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: cyan
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: cyan
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  font:
    text: Manrope
    code: Fira Mono
  icon:
    logo: fontawesome/solid/flask
  favicon: images/flask.svg

# Plugins
plugins:
  - search
  - minify:
      minify_html: true
  - redirects:
      redirect_maps:
        lab-examples/tls-cert.md: https://clabs.netdevops.me/security/gnmitls/

# Customization
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/hellt
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/ntdvps
    - icon: fontawesome/brands/discord
      link: https://discord.gg/vAyddtaEV9
  analytics:
    provider: google
    property: G-368XR9X5MG

extra_css:
  - stylesheets/extra.css

# Extensions
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.attr_list
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: "#"
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      linenums_style: pymdownx-inline
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols:
      fractions: false
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
