site_name: containerlab
nav:
  - Home: index.md
  - Installation: install.md
  - Quick start: quickstart.md
  - User manual:
      - Topology definition: manual/topo-def-file.md
      - Nodes: manual/nodes.md
      - Kinds:
          - About: manual/kinds/kinds.md
          - srl - Nokia SR Linux: manual/kinds/srl.md
          - crpd - Juniper cRPD: manual/kinds/crpd.md
          - ceos - Arista cEOS: manual/kinds/ceos.md
          - sonic-vs - SONiC: manual/kinds/sonic-vs.md
          - vr-sros - Nokia SR OS: manual/kinds/vr-sros.md
          - vr-vmx - Juniper vMX: manual/kinds/vr-vmx.md
          - vr-xrv9k - Cisco XRv9k: manual/kinds/vr-xrv9k.md
          - vr-xrv - Cisco XRv: manual/kinds/vr-xrv.md
      - Configuration artifacts: manual/conf-artifacts.md
      - Network wiring concepts: manual/network.md
      - Packet capture & Wireshark: manual/wireshark.md
      - VM based routers integration: manual/vrnetlab.md
      - Share lab access: manual/shared-sockets.md
  - Command reference:
      - deploy: cmd/deploy.md
      - destroy: cmd/destroy.md
      - inspect: cmd/inspect.md
      - save: cmd/save.md
      - generate: cmd/generate.md
      - graph: cmd/graph.md
      - tools:
          - disable-tx-offload: cmd/tools/disable-tx-offload.md
  - Lab examples:
      - About: lab-examples/lab-examples.md
      - Single SR Linux node: lab-examples/single-srl.md
      - Two SR Linux nodes: lab-examples/two-srls.md
      - 3-nodes CLOS: lab-examples/min-clos.md
      - 5-stage CLOS: lab-examples/min-5clos.md
      - Nokia SR Linux and Arista cEOS: lab-examples/srl-ceos.md
      - Nokia SR Linux and Juniper cRPD: lab-examples/srl-crpd.md
      - Nokia SR Linux and SONiC: lab-examples/srl-sonic.md
      - External bridge capability: lab-examples/ext-bridge.md
      - WAN topology: lab-examples/wan.md
      - Nokia SR Linux and Nokia SR OS: lab-examples/vr-sros.md
      - Nokia SR Linux and Juniper vMX: lab-examples/vr-vmx.md
      - Nokia SR Linux and Cisco XRv9k: lab-examples/vr-xrv9k.md
      - Nokia SR Linux and Cisco XRv: lab-examples/vr-xrv.md
      - Nokia SR Linux and FRR: lab-examples/srl-frr.md

site_author: Roman Dodin
site_description: >-
  Containerlab deploys docker based meshed lab topologies
# Repository
repo_name: srl-wim/container-lab
repo_url: https://github.com/srl-wim/container-lab
edit_uri: ""
theme:
  name: material

  # 404 page
  static_templates:
    - 404.html

  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true

  language: en
  palette:
    scheme: preference
    primary: white
    accent: cyan
  font:
    text: Manrope
    code: Fira Mono
  icon:
    logo: fontawesome/solid/flask
  favicon: images/flask.svg

# Plugins
plugins:
  - search
  - minify:
      minify_html: true

# Customization
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/hellt
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/ntdvps

# Extensions
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.attr_list
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: "#"
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      linenums_style: pymdownx-inline
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

google_analytics:
  - UA-101537614-3
  - auto
